//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
      
        public int AdminId { get; set; }
            [Required]
            public string AdminEmail { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string AdminPassword { get; set; }
        public bool RememberMe { get; set; }
    }
}
