//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentText { get; set; }
        public int rating { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual PlacesToVisit PlacesToVisit { get; set; }
        public virtual User User { get; set; }
    }
}
